purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7614845905918628
  brandStrength: 0.1396734709851444
  lightness: 0.4076474297326058
  brandColors:
    - '#D9DADC'
    - '#494846'
    - '#B0B3BA'
    - '#8494A1'
    - '#833742'
  rhythmicContrast: 0.4993564502801746
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: PeterKelly
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9857603157870471
layout_spectrum: 0.2110634
