name: PeterKelly
favicon: null
layout_spectrum: 0.3561711893416941
typography_spectrum: 0.9857603157870471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.13967347098514438
  lightness: 0.4076474297326058
  saturation: 0.7614845905918628
  rhythmicContrast: 0.4993564502801746
purpose: []
